---
- name: get list of active repositories
  command: yum repolist
  args:
    warn: false
  register: yum_repolist
  changed_when: false
  check_mode: false

- name: enable highavailability repository (CentOS 8.1/8.2)
  ini_file:
    dest: '/etc/yum.repos.d/CentOS-HA.repo'
    section: 'HighAvailability'
    option: 'enabled'
    value: '1'
    create: 'no'
    mode: '0644'
  when: >-
    'HighAvailability' not in yum_repolist.stdout
    and enable_repos | bool
    and ansible_distribution_version in ['8.1', '8.2']

- name: enable highavailability repository (CentOS 8.3+)
  ini_file:
    dest: '/etc/yum.repos.d/CentOS-Linux-HighAvailability.repo'
    section: 'ha'
    option: 'enabled'
    value: '1'
    create: 'no'
    mode: '0644'
  when: >-
    'HighAvailability' not in yum_repolist.stdout
    and enable_repos | bool
    and ansible_distribution_major_version in ['8']
    and ansible_distribution_version not in ['8.0', '8.1', '8.2', '8']

- name: enable highavailability repository (CentOS 8 Stream)
  ini_file:
    dest: '/etc/yum.repos.d/CentOS-Stream-HighAvailability.repo'
    section: 'ha'
    option: 'enabled'
    value: '1'
    create: 'no'
    mode: '0644'
  when: >-
    'HighAvailability' not in yum_repolist.stdout
    and enable_repos | bool
    and ansible_distribution_major_version in ['8']
    and ansible_distribution_version not in ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
